


# Permalinks
permalink:        pretty

# Setup
title:            The DSE data model
tagline:          'Modeling Diplomatic Scholarly Editions'
description:      ''


baseurl: '/dse/'


author:
  name:           'Neel Smith'


links:
  - title:  CITE Architecture home
    url:  https://cite-architecture.github.io/
    external: true
  - title:  DSE Github repository
    url:  https://github.com/cite-architecture/dse
    external: true
